defaults:
  - _self_
  # default slurm configuration set here
  - slurm: default
  # default multirun launcher DO NOT CHANGE
  - hydra/launcher: slurm

# By default, we store logs into a directory hydra/ in your home directory, indexed
# by job name and time. This can be changed to whatever directory you'd like
hydra:
  run:
    dir: /h/${env:USER}/hydra/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S-%N}
  sweep:
    dir: /h/${env:USER}/hydra/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S-%N}
    subdir: ${hydra.job.num}


# virtual environment to run with. If using conda, uncomment the conda arg and comment out venv
venv: vqvae
#conda: ~

# max running jobs, -1 means no limit
max_running: -1

# max pending jobs, -1 means no limit
max_pending: -1

# max total jobs
max_total: 380

# extra strings to make job names unique
extra: ~

# run command line scripts
command: ~
