# @package _group_

# date that job was run on. populated automatically but can be manually set
date: ~

# CPUs per task set as 4 * GPU count by default
cpus_per_task: eval:4*int("${slurm.gres}"[-1])

# nodes to exclude from launching jobs on
exclude: ~

# GPUs to use
gres: gpu:1

# list of identifiers for job name. concatenated with "_" to generate
# full job name. by default, set to the name of script and any extra
# identifiers passed in. typically we would include model name, data
# name, etc. here. fields can be populated automatically by interpolation
job_name:
  - eval:sys.argv[0][:-3].split('/')[-1]
  - ${extra}

# amount of memory to request, 20 * GPU count gigabytes by default
mem: eval:str(20*int("${slurm.gres}"[-1]))+'G'

# number of nodes to run on. increase this if running multinode jobs
nodes: 1

# number of tasks per node 
ntasks_per_node: 1

# append to rather than overwrite log files when restarting preempted jobs
open_mode: append

# partitions to run on
partition: rtx6000,t4v2,t4v1

# account to run with
account: ~

# slurm QOS
qos: normal

