defaults:
  - db: mysql
  - override hydra/launcher: slurm

tags: ~

hydra:
  launcher:
    cpus_per_task: 3
    mem: 25G
    partition: gpu
    gres: gpu:1
##### SUGGESTED HYDRA CONFIG ###########################
  sweep: 
    # subdir is built dynamically using the tags
    dir: ${oc.env:HOME}/slurm/${oc.select:hydra.launcher.date,${now:%Y-%m-%d}}/${hydra.job.name}
  run:
    # once we're running set tags from conf
    dir: ${hydra.sweep.dir}/${join:${tags}}
########################################################
