defaults:
  - db: mysql
  - override hydra/launcher: slurm

tags: ~

##### SUGGESTED HYDRA CONFIG ###########################
hydra:
  launcher:
    cpus_per_task: 3
    mem: 25G
    partition: gpu
    gres: gpu:1
  sweep: 
    # subdir is built dynamically using the tags
    dir: ${oc.env:HOME}/slurm/${now:%Y-%m-%d}/${hydra.job.name}
  run:
    # once we're running set tags from conf
    dir: ${hydra.sweep.dir}/${join:${oc.select:tags,[]}}
########################################################
